/**
* ActionTypes
* @const {String}
*/
const ActionTypes = {
    GET_CURRENT_ACCOUNT: 'GET_CURRENT_ACCOUNT',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SET_SELECTED_COLLECTION_ITEM: 'SET_SELECTED_COLLECTION_ITEM',
    TOGGLE_BUILDER: 'TOGGLE_BUILDER',
    ATTACH_RPG_CHARACTER: 'ATTACH_RPG_CHARACTER',
};

export default ActionTypes;
