name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies

    # HACK: need a specific version while using experimental branch, not available via homebrew
    # - name: Set up Homebrew
    #   id: set-up-homebrew
    #   uses: Homebrew/actions/setup-homebrew@master
    # - run: brew install flow-cli
    - run: sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v0.45.1-cadence-attachments-3
    - run: flow version
    # END HACK

    - run: npm ci
    
    # Build
    - run: npm run build

    # Validate
    - run: npm run check
    - run: npm test
